# Generated by Django 2.0.4 on 2018-05-18 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=17)),
                ('ie', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=70)),
                ('tipo_cliente', models.CharField(max_length=7)),
                ('segmento', models.CharField(max_length=40)),
                ('nome_contato', models.CharField(max_length=70)),
                ('e_mail', models.CharField(max_length=60)),
                ('rua', models.CharField(blank=True, max_length=30, null=True)),
                ('bairro', models.CharField(blank=True, max_length=20, null=True)),
                ('numero', models.SmallIntegerField(blank=True, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cidade', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone1', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone2', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField(max_length=20)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=17, unique=True)),
                ('razao_social', models.CharField(max_length=80, unique=True)),
                ('nome_fantasia', models.CharField(max_length=50)),
                ('ie', models.CharField(max_length=15)),
                ('data_cadastro', models.DateField(blank=True, null=True)),
                ('categoria', models.CharField(max_length=30)),
                ('nome_contato', models.CharField(max_length=30)),
                ('rua', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=20)),
                ('numero', models.IntegerField()),
                ('cep', models.BigIntegerField()),
                ('complemento', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=40)),
                ('telefone1', models.CharField(max_length=20)),
                ('telefone2', models.CharField(blank=True, max_length=20, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=85, null=True)),
                ('slug', models.SlugField(max_length=20)),
            ],
            options={
                'db_table': 'Fornecedor',
            },
        ),
        migrations.CreateModel(
            name='FornecedorMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_fornecedor', models.ForeignKey(db_column='id_fornecedor', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Fornecedor')),
            ],
            options={
                'db_table': 'FonecedorMaterial',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(blank=True, max_length=20, null=True)),
                ('nome', models.CharField(max_length=70)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('qtd', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Material',
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(max_length=30)),
                ('detalhes', models.CharField(max_length=30)),
                ('prazo', models.DateField()),
                ('entrega', models.CharField(blank=True, max_length=60, null=True)),
                ('custo_frete', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('margem', models.IntegerField(blank=True, null=True)),
                ('valor_orçamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_contato', models.DateField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Cliente')),
            ],
            options={
                'db_table': 'Orcamento',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rastreio', models.CharField(max_length=50)),
                ('data_entregue', models.DateField(blank=True, null=True)),
                ('pagamento', models.CharField(blank=True, max_length=85, null=True)),
                ('situacao', models.CharField(blank=True, max_length=30, null=True)),
                ('data_confirmado', models.DateField(blank=True, null=True)),
                ('id_orcamento', models.ForeignKey(db_column='id_orcamento', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Orcamento')),
            ],
            options={
                'db_table': 'Projeto',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.SmallIntegerField(blank=True, null=True)),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nome', models.CharField(blank=True, max_length=70, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('id_projeto', models.ForeignKey(db_column='id_projeto', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Projeto')),
            ],
            options={
                'db_table': 'Servico',
            },
        ),
        migrations.AddField(
            model_name='fornecedormaterial',
            name='id_material',
            field=models.ForeignKey(db_column='id_material', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Material'),
        ),
        migrations.AlterUniqueTogether(
            name='fornecedor',
            unique_together={('ie', 'estado')},
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('ie', 'estado'), ('cpf_cnpj', 'estado')},
        ),
        migrations.AlterUniqueTogether(
            name='fornecedormaterial',
            unique_together={('id_material', 'id_fornecedor')},
        ),
    ]
